flask/blog_login/models.py
# -*- coding: utf-8 -*-

from datetime import date, datetime
from app import db

from werkzeug.security import (
    generate_password_hash,
    check_password_hash,
)


class User(db.Model):
    id = db.Column('id', db.Integer, primary_key=True)
    username = db.Column('username', db.String(20), unique=True, index=True)
    password = db.Column('password', db.String(10))
    email = db.Column('email', db.String(50), unique=True, index=True)
    registered_on = db.Column('registered_on', db.DateTime)

    def __init__(self, username=None, email=None):
        self.username = username
        # we do not store original password.
        self.email = email
        self.registered_on = datetime.utcnow()

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<%s>' % self.username


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship(
        'User', backref=db.backref('posts', lazy='dynamic')
    )

    title = db.Column(db.String(140), unique=True)
    content = db.Column(db.String(3000))

    date_created = db.Column(db.Date, default=date.today())
    is_visible = db.Column(db.Boolean, default=True)

    def __init__(self, title='', content='', user=None,
                 date_created=None, is_visible=None):
        self.title = title
        self.content = content
        self.user = user

        if date_created is not None:
            self.date_created = date_created

        if is_visible is not None:
            self.is_visible = is_visible

flask/blog_login/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms_alchemy import model_form_factory
from wtforms import PasswordField, StringField
from wtforms.validators import Email, length

from models import User, Post

BaseModelForm = model_form_factory(Form)


def passwords_match(form, field):
    if form.password.data != field.data:
        raise ValueError('Passwords do not match')


class RegisterForm(BaseModelForm):
    class Meta:
        model = User

        only = ['username', 'email']

        validators = {
            'email': [Email()],
        }

    password = PasswordField()
    repeat_password = PasswordField(validators=[
        passwords_match,
    ])


class LoginForm(Form):
    username = StringField()
    password = PasswordField()

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self, *args, **kwargs):
        rv = super(LoginForm, self).validate()
        if not rv:
            return False

        user = User.query.filter_by(
            username=self.username.data).first()
        if user is None:
            self.username.errors.append('Unknown username')
            return False

        if not user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        self.user = user
        return True


class AddPostForm(BaseModelForm):
    class Meta:
        model = Post

        only = ['title', 'content']

        validators = {
            'title': [length(min=1)],
        }

flask/blog_login/app.py
# -*- coding: utf-8 -*-

from flask import Flask, request, flash, redirect, render_template, url_for
from flask_sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager


import config

login_manager = LoginManager()
app = Flask(__name__, template_folder='templates')
app.config.from_object(config)

#bower = Blueprint('bower', __name__, )

db = SQLAlchemy(app)


@login_manager.user_loader
def load_user(user_id):
    from models import User

    return User.query.get(user_id)



@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('auth.login'))
    # return 'Unauthorized', 401


if __name__ == '__main__':
    from models import *
    from views import auth, views
    # Blueprints:
    app.register_blueprint(auth)
    app.register_blueprint(views)

    db.create_all()

# Custom modules:
    login_manager.init_app(app)
    app.run()

flask/blog_login/views.py
# -*- coding: utf-8 -*-
from flask import (
    Blueprint,
    request,
    redirect,
    render_template,
    flash,
    url_for,
)
from flask.ext.login import (
    login_required,
    login_user,
    logout_user,
    current_user,
)

from models import User
from app import db
from forms import RegisterForm, LoginForm, AddPostForm


auth = Blueprint('auth', __name__, url_prefix='/auth')
views = Blueprint('views', __name__, url_prefix='/')


# Views:


@views.route('/', methods=['GET'])
def index():
    from models import Post

    posts = Post.query.filter_by(is_visible=True).all()
    return render_template('view.html', form=None, posts=posts)





# Auth:


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html', form=RegisterForm())

    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        user.set_password(form.password.data)

        db.session.add(user)
        db.session.commit()

        flash('User successfully registered')
        return redirect(url_for('.login'))
    else:
        flash('Incorrect registration!')
        return render_template('register.html', form=form)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html', form=LoginForm())

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = form.user
        login_user(user, remember=True)
        return redirect(url_for('auth.view'))
    else:
        flash('Incorrect attempt!')
        return render_template('login.html', form=form)


@auth.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return 'You are now logged out'


@auth.route('/view', methods=['GET', 'POST'])
@login_required
def view():
    from models import User, Post

    if request.method == 'POST':

        form = AddPostForm(request.form)
        if form.validate():

            post = Post(title=form.data['title'], content=form.data['content'], user=current_user)
            post.is_visible = True

            print("{} is creating a new {}'th post!".format(
               post.user.username, len(post.user.posts.all()) + 1))
            print post.id

            db.session.add(post)
            db.session.commit()
            flash('Post created!')

        else:
            flash('Form is not valid! Post was not created.')

    else:
        form = AddPostForm()

    posts = Post.query.filter_by(is_visible=True).all()
    return render_template('home.html', form=form, posts=posts)


@auth.route('/<post_id>/delete', methods=['GET'])
@login_required
def delete(post_id):
    from models import User, Post

    form = AddPostForm(request.form)
    post = Post.query.filter_by(id=post_id).first()
    print post.id
    post.is_visible = False
    db.session.commit()
    posts = Post.query.filter_by(is_visible=True).all()
    return render_template('home.html', posts=posts, form=form)

flask/blog_login/templates/_base_form.html
{% extends '_base_template.html' %}

{% block content %}

<div class="content">
    <h2>{% block content_title %}{% endblock %}</h2>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class=flashes>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% from "macros/render_field.html" import render_field %}
    <form method="POST" action="{% block form_url %}{% endblock %}">
        {{ form.hidden_tag() }}
        <dl>
            {% for field in form %}
                {% if field.id != 'csrf_token' %}
                    {{ render_field(field) }}
                {% endif %}
            {% endfor %}
        </dl>

        <input type="submit" value="Submit" class="btn">
    </form>

</div>

{% endblock %}

flask/blog_login/templates/_base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блоги</title>

    <link rel="stylesheet" href="{{ url_for('bower.static', filename='bootstrap/dist/css/bootstrap.min.css')}}">
</head>
<body>

<h1>Добро пожаловать в мой блог!</h1>

{% block content %}
{% endblock %}

</body>
</html>

flask/blog_login/templates/add_comment.html
{% extends '_base_template.html' %}

{% block content %}
<div class="menu">

        <a class="btn btn-primary" href="{{ url_for('auth.logout') }}" role="button">Logout</a>

</div>
<div class="content">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class=flashes>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% from "macros/render_field.html" import render_field %}
    <form method="POST" action="{{ url_for('auth.view') }}">
        {{ form.hidden_tag() }}
        <dl>
            {% for field in form %}
                {% if field.id != 'csrf_token' and field.id != 'is_visible' and
            field.id != 'date_created' and field.id != 'content' %}
                    {{ render_field(field) }}
            {% endif %}
            {% if field.id == 'content' %}
                <dt>{{ field.label }}</dt>
                <dd>{{ field()|safe }} </dd>
            {% endif %}
            {% endfor %}

        </dl>

        <input type="submit" value="{{ 'Submit' }}" class="btn">
    </form>

    <div class="posts">
        {% for item in posts %}
             <div class="row">
             <div class="col-sm-10 col-md-8">
                <div class="thumbnail">
                  <img >
                  <div class="caption">
                    <h3>{{ item.title }}</h3>
                      <h4>{{ item.user.username }}</h4>
                      <h5>{{ item.date_created }}</h5>
                    <p>{{ item.content }}</p>
                    <p><a href="{{ url_for('auth.delete', post_id=item.id) }}" class="btn btn-primary" role="button">Delete</a>
                    <a href="{{ url_for('auth.add_comment', post_id=item.id) }}" class="btn btn-default" role="button">Delete</a>
                   </p>
                  </div>
                </div>
              </div>
            </div>

        {% endfor %}
    </div>

</div>

{% endblock %}

flask/blog_login/templates/home.html
{% extends '_base_template.html' %}

{% block content %}
<div class="menu">

        <a class="btn btn-primary" href="{{ url_for('auth.logout') }}" role="button">Logout</a>

</div>
<div class="content">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class=flashes>
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% from "macros/render_field.html" import render_field %}
    <form method="POST" action="{{ url_for('auth.view') }}">
        {{ form.hidden_tag() }}
        <dl>
            {% for field in form %}
                {% if field.id != 'csrf_token' and field.id != 'is_visible' and field.id != 'date_created' %}
                    {{ render_field(field) }}
                {% endif %}
            {% endfor %}
        </dl>

        <input type="submit" value="{{ 'Submit' }}" class="btn">
    </form>

    <div class="posts">
        {% for item in posts %}
             <div class="row">
             <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img >
                  <div class="caption">
                    <h3>{{ item.title }}</h3>
                      <h4>{{ item.user.username }}</h4>
                      <h5>{{ item.date_created }}</h5>
                    <p>{{ item.content }}</p>
                    <p><a href="{{ url_for('auth.delete', post_id=item.id) }}" class="btn btn-primary" role="button">Delete</a> </p>
                  </div>
                </div>
              </div>
            </div>

        {% endfor %}
    </div>

</div>

{% endblock %}

flask/blog_login/templates/login.html
{% extends '_base_form.html' %}

{% block content_title %}
    Login
{% endblock %}

{% block form_url %}
    {{ url_for('auth.login') }}
{% endblock %}

flask/blog_login/templates/macros/render_field.html
{% macro render_field(field) %}
  <dt>{{ field.label }}</dt>
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

flask/blog_login/templates/register.html
{% extends '_base_form.html' %}

{% block content_title %}
    Register
{% endblock %}

{% block form_url %}
    {{ url_for('auth.register') }}
{% endblock %}

flask/blog_login/templates/view.html
{% extends '_base_template.html' %}

{% block content %}
<div class="menu">

        <a class="btn btn-default" href="{{ url_for('auth.login') }}" role="button">Login</a>
     <a class="btn btn-primary" href="{{ url_for('auth.register') }}" role="button">Register</a>

</div>
<div class="content">

    <div class="posts">
        {% for item in posts %}
            <div class="row">
             <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <img >
                  <div class="caption">
                    <h3>{{ item.title }}</h3>
                      <h4>{{ item.user.username }}</h4>
                      <h5>{{ item.date_created }}</h5>
                    <p>{{ item.content }}</p>
                   </div>
                </div>
              </div>
            </div>

        {% endfor %}
    </div>

</div>

{% endblock %}